### ISSUE TITLE
Ember Data and ajaxOptions

### ISSUE THREAD

**Issue by thec0keman** [truenorth/ember-api-actions#2]
Ember Data calls `adapter.ajaxOptions` within the `ajax` method.  Since both `instanceOp` and `classOp` use this method the data payload gets run through  `JSON.stringify` twice.  This can be very confusing for a backend (at least in the case of Rails, it doesn't parse it at all).

Would it work to only pass in custom options + the data payload into ajax instead of running them through `adapter.ajaxOptions`?

**Comment by truenorth** [comment]
this sounds like a real concern, and your proposed solution is reasonable. Let me work up a few test cases and see if I can get in a fix today

**Comment by truenorth** [comment]
@thec0keman - Just published a `v0.0.3` that fixes this issue. Thanks for reporting this problem

**Comment by thec0keman** [comment]
Thanks for the quick fix!
